agents:
  number_preys: 1
  #
  number_predators: 2
  #
  gamma: 0.9
  #
  epsilon_greedy: 0.01
  #
  lr: 0.01
  #
  nbre_actions: 5
  #
  update_frequency: 20
  #
  update_type: hard

replay_memory:
  size: 10000
  shuffle: No